In [1]:
import pandas as pd
import geopandas as gpd

pd.set_option("display.max_columns", None)

In [ ]:
man_gdf = gpd.read_parquet("data/Cartografia_censo2024_Pais_Manzanas.parquet")
# man_gdf["d_per"] = man_gdf.n_per * 10000 / man_gdf.to_crs(32718).area
man_gdf = man_gdf[man_gdf.COMUNA == "CONCEPCIÓN"]
man_gdf

,OBJECTID,CUT,COD_REGION,REGION,COD_PROVINCIA,PROVINCIA,COMUNA,AREA_C,MANZENT,DISTRITO,COD_DISTRITO,COD_LOCALIDAD,COD_ZONA,LOCALIDAD,COD_ENTIDAD,COD_MANZANA,ENTIDAD,TIPO_MZ,COD_CATEGORIA,CATEGORIA,MZ_BASE_CENSO,ID_ENTIDAD,ID_LOCALIDAD,ID_DISTRITO,ID_ZONA,n_per,n_hombres,n_mujeres,n_edad_0_5,n_edad_6_13,n_edad_14_17,n_edad_18_24,n_edad_25_44,n_edad_45_59,n_edad_60_mas,prom_edad,n_inmigrantes,n_nacionalidad,n_pueblos_orig,n_afrodescendencia,n_lengua_indigena,n_religion,n_dificultad_ver,n_dificultad_oir,n_dificultad_mover,n_dificultad_cogni,n_dificultad_cuidado,n_dificultad_comunic,n_discapacidad,n_estcivcon_casado,n_estcivcon_conviviente,n_estcivcon_conv_civil,n_estcivcon_anul_sep_div,n_estcivcon_viudo,n_estcivcon_soltero,prom_escolaridad18,n_asistencia_parv,n_asistencia_basica,n_asistencia_media,n_asistencia_superior,n_cine_nunca_curso_primera_infancia,n_cine_primaria,n_cine_secundaria,n_cine_terciaria_maestria_doctorado,n_cine_especial_diferencial,n_analfabet,n_ocupado,n_desocupado,n_fuera_fuerza_trabajo,n_cise_rec_independientes,n_cise_rec_dependientes,n_cise_rec_trabajador_no_remunerado,n_ciuo_1,n_ciuo_2,n_ciuo_3,n_ciuo_4,n_ciuo_5,n_ciuo_6,n_ciuo_7,n_ciuo_8,n_ciuo_9,n_ciuo_0,n_caenes_A,n_caenes_B,n_caenes_C,n_caenes_D,n_caenes_E,n_caenes_F,n_caenes_G,n_caenes_H,n_caenes_I,n_caenes_J,n_caenes_K,n_caenes_L,n_caenes_M,n_caenes_N,n_caenes_O,n_caenes_P,n_caenes_Q,n_caenes_R,n_caenes_S,n_caenes_T,n_caenes_U,n_transporte_auto,n_transporte_publico,n_transporte_camina,n_transporte_bicicleta,n_transporte_motocicleta,n_transporte_cab_lan_bote,n_transporte_otros,n_hog,prom_per_hog,n_hog_unipersonales,n_hog_60,n_hog_menores,n_jefatura_mujer,n_tenencia_propia_pagada,n_tenencia_propia_pagandose,n_tenencia_arrendada_contrato,n_tenencia_arrendada_sin_contrato,n_tenencia_cedida_trabajo,n_tenencia_cedida_familiar,n_tenencia_otro,n_comb_cocina_gas,n_comb_cocina_parafina,n_comb_cocina_lena,n_comb_cocina_pellet,n_comb_cocina_carbon,n_comb_cocina_electricidad,n_comb_cocina_solar,n_comb_cocina_no_utiliza,n_comb_calefaccion_gas,n_comb_calefaccion_parafina,n_comb_calefaccion_lena,n_comb_calefaccion_pellet,n_comb_calefaccion_carbon,n_comb_calefaccion_electricidad,n_comb_calefaccion_otra,n_comb_calefaccion_no_utiliza,n_serv_tel_movil,n_serv_compu,n_serv_tablet,n_serv_internet_fija,n_serv_internet_movil,n_serv_internet_satelital,n_internet,n_vp,n_vp_ocupada,n_vp_desocupada,n_tipo_viv_casa,n_tipo_viv_depto,n_tipo_viv_indigena,n_tipo_viv_pieza,n_tipo_viv_mediagua,n_tipo_viv_movil,n_tipo_viv_otro,n_dormitorios_1,n_dormitorios_2,n_dormitorios_3,n_dormitorios_4,n_dormitorios_5,n_dormitorios_6_o_mas,n_viv_hacinadas,n_viv_irrecuperables,n_hog_allegados,n_nucleos_hacinados_allegados,n_viv_no_ampliables,n_deficit_cuantitativo,n_mat_paredes_hormigon,n_mat_paredes_albanileria,n_mat_paredes_tabique_forrado,n_mat_paredes_tabique_sin_forro,n_mat_paredes_artesanal,n_mat_paredes_precarios,n_mat_techo_tejas,n_mat_techo_hormigon,n_mat_techo_zinc,n_mat_techo_fibrocemento,n_mat_techo_fonolita,n_mat_techo_paja,n_mat_techo_precarios,n_mat_techo_sin_cubierta,n_mat_piso_radier_con_revestimiento,n_mat_piso_radier_sin_revestimiento,n_mat_piso_baldosa_cemento,n_mat_piso_capa_cemento,n_mat_piso_tierra,n_fuente_agua_publica,n_fuente_agua_pozo,n_fuente_agua_camion,n_fuente_agua_rio,n_distrib_agua_llave,n_distrib_agua_llave_fuera,n_distrib_agua_acarreo,n_serv_hig_alc_dentro,n_serv_hig_alc_fuera,n_serv_hig_fosa,n_serv_hig_pozo,n_serv_hig_acequia_canal,n_serv_hig_cajon_otro,n_serv_hig_bano_quimico,n_serv_hig_bano_seco,n_serv_hig_no_tiene,n_fuente_elect_publica,n_fuente_elect_diesel,n_fuente_elect_solar,n_fuente_elect_eolica,n_fuente_elect_otro,n_fuente_elect_no_tiene,n_basura_servicios,n_basura_entierra,n_basura_eriazo,n_basura_rio,n_basura_otro,SHAPE_Length,SHAPE_Area,SHAPE
19454,19455,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,URBANO,8.101011e+12,INTENDENCIA,1,7,1,GRAN CONCEPCIÓN,1,1,CONCEPCIÓN,URBANO,1,Ciudad,1,8.101007e+11,81011007.0,810101.0,810101001.0,19.0,15.0,4.0,1.0,0.0,0.0,1.0,6.0,6.0,5.0,48.8,4.0,4.0,NaN,0.0,NaN,10.0,0.0,0.0,2.0,2.0,2.0,3.0,3.0,6.0,4.0,0.0,1.0,0.0,7.0,14.4,0.0,0.0,0.0,0.0,1.0,2.0,9.0,7.0,0.0,0.0,13.0,0.0,5.0,4.0,8.0,1.0,2.0,3.0,1.0,0.0,5.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,7.0,2.7,1.0,1.0,1.0,2.0,2.0,0.0,3.0,0.0,2.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,1.0,0.0,0.0,2.0,0.0,0.0,6.0,5.0,3.0,6.0,6.0,0.0,7.0,7.0,7.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,7.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.004666,1.397748e-06,"MULTIPOLYGON (((-73.048 -36.82416, -73.04797 -..."
19455,19456,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,URBANO,8.101011e+12,INTENDENCIA,1,7,1,GRAN CONCEPCIÓN,1,2,CONCEPCIÓN,URBANO,1,Ciudad,1,8.101007e+11,81011007.0,810101.0,810101001.0,71.0,24.0,47.0,4.0,2.0,0.0,8.0,34.0,5.0,18.0,40.9,5.0,NaN,4.0,0.0,NaN,29.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,8.0,14.0,2.0,4.0,7.0,30.0,14.4,4.0,2.0,0.0,3.0,4.0,14.0,10.0,43.0,0.0,0.0,44.0,7.0,14.0,42.0,1.0,1.0,5.0,21.0,6.0,1.0,7.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1.0,2.0,0.0,1.0,0.0,5.0,1.0,2.0,9.0,5.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,43.0,1.7,26.0,13.0,4.0,26.0,3.0,0.0,40.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,35.0,0.0,0.0,1.0,3.0,0.0,1.0,0.0,37.0,0.0,1.0,43.0,33.0,10.0,27.0,37.0,0.0,40.0,57.0,43.0,14.0,15.0,42.0,0.0,0.0,0.0,0.0,0.0,23.0,14.0,3.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,3.0,3.0,42.0,0.0,1.0,0.0,0.0,0.0,4.0,36.0,3.0,0.0,0.0,0.0,0.0,0.0,43.0,0.0,0.0,0.0,0.0,43.0,0.0,0.0,0.0,43.0,0.0,0.0,43.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0,0.0,0.0,0.0,0.0,0.0,43.0,0.0,0.0,0.0,0.0,0.004765,1.450461e-06,"MULTIPOLYGON (((-73.0493 -36.82464, -73.04927 ..."
19456,19457,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,URBANO,8.101011e+12,INTENDENCIA,1,7,1,GRAN CONCEPCIÓN,1,3,CONCEPCIÓN,URBANO,1,Ciudad,1,8.101007e+11,81011007.0,810101.0,810101001.0,203.0,91.0,112.0,4.0,12.0,8.0,23.0,66.0,32.0,58.0,44.1,22.0,17.0,13.0,0.0,4.0,110.0,13.0,7.0,9.0,7.0,5.0,1.0,29.0,33.0,42.0,2.0,15.0,12.0,82.0,15.2,3.0,12.0,8.0,17.0,5.0,35.0,60.0,103.0,0.0,0.0,110.0,5.0,71.0,36.0,74.0,0.0,12.0,51.0,11.0,4.0,16.0,1.0,3.0,1.0,3.0,0.0,1.0,1.0,3.0,0.0,0.0,1.0,14.0,5.0,5.0,6.0,1.0,3.0,12.0,3.0,5.0,19.0,11.0,3.0,3.0,0.0,0.0,16.0,22.0,39.0,8.0,1.0,0.0,4.0,102.0,2.0,45.0,32.0,12.0,51.0,25.0,7.0,57.0,7.0,0.0,5.0,1.0,94.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,26.0,15.0,1.0,0.0,0.0,53.0,0.0,7.0,101.0,85.0,43.0,84.0,96.0,2.0,100.0,129.0,103.0,26.0,4.0,125.0,0.0,0.0,0.0,0.0,0.0,26.0,33.0,36.0,1.0,1.0,0.0,1.0,0.0,5.0,0.0,1.0,6.0,93.0,3.0,1.0,0.0,0.0,0.0,2.0,91.0,4.0,0.0,0.0,0.0,0.0,0.0,97.0,0.0,0.0,0.0,0.0,97.0,0.0,0.0,0.0,97.0,0.0,0.0,97.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97.0,0.0,0.0,0.0,0.0,0.0,97.0,0.0,0.0,0.0,0.0,0.004664,1.398813e-06,"MULTIPOLYGON (((-73.04621 -36.82468, -73.0467 ..."
19457,19458,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,URBANO,8.101011e+12,INTENDENCIA,1,7,1,GRAN CONCEPCIÓN,1,4,CONCEPCIÓN,URBANO,1,Ciudad,1,8.101007e+11,81011007.0,810101.0,810101001.0,43.0,19.0,24.0,5.0,1.0,1.0,4.0,17.0,11.0,4.0,35.8,5.0,13.0,NaN,0.0,NaN,28.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,11.0,4.0,4.0,1.0,2.0,15.0,13.1,4.0,0.0,1.0,3.0,5.0,7.0,21.0,10.0,0.0,0.0,23.0,6.0,8.0,23.0,0.0,0.0,4.0,3.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,18.0,2.4,7.0,2.0,5.0,9.0,6.0,0.0,11.0,0.0,0.0,0.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,8.0,0.0,1.0,16.0,10.0,5.0,14.0,7.0,0.0,17.0,25.0,18.0,7.0,23.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,8.0,4.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,16.0,1.0,1.0,0.0,0.0,0.0,5.0,12.0,1.0,0.0,0.0,0.0,0.0,0.0,13.0,5.0,0.0,0.0,0.0,18.0,0.0,0.0,0.0,18.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.004729,1.430171e-06,"MULTIPOLYGON (((-73.05043 -36.82521, -73.04938..."
19458,19459,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,URBANO,8.101011e+12,INTENDENCIA,1,7,1,GRAN CONCEPCIÓN,1,5,CONCEPCIÓN,URBANO,1,Ciudad,1,8.101007e+11,81011007.0,810101.0,810101001.0,133.0,60.0,73.0,3.0,4.0,5.0,21.0,39.0,24.0,37.0,43.3,8.0,8.0,15.0,0.0,NaN,86.0,8.0,2.0,4.0,3.0,3.0,0.0,12.0,23.0,28.0,0.0,14.0,4.0,56.0,15.1,1.0,3.0,4.0,19.0,3.0,13.0,59.0,57.0,1.0,1.0,69.0,4.0,52.0,35.0,34.0,0.0,8.0,24.0,10.0,1.0,12.0,0.0,6.0,3.0,4.0,0.0,1.0,0.0,7.0,0.0,0.0,3.0,8.0,1.0,4.0,2.0,0.0,1.0,9.0,1.0,0.0,10.0,9.0,0.0,3.0,1.0,0.0,5.0,25.0,30.0,3.0,0.0,0.0,0.0,70.0,1.9,29.0,17.0,7.0,47.0,18.0,6.0,36.0,5.0,0.0,5.0,0.0,58.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,7.0,9.0,0.0,0.0,0.0,35.0,0.0,19.0,70.0,51.0,30.0,22.0,67.0,0.0,67.0,100.0,73.0,27.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,21.0,37.0,8.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,63.0,4.0,0.0,0.0,0.0,0.0,3.0,60.0,4.0,0.0,0.0,0.0,0.0,0.0,67.0,0.0,0.0,0.0,0.0,67.0,0.0,0.0,0.0,67.0,0.0,0.0,67.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67.0,0.0,0.0,0.0,0.0,0.0,67.0,0.0,0.0,0.0,0.0,0.006081,1.394383e-06,"MULTIPOLYGON (((-73.04795 -36.82438, -73.04797..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208179,208180,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,RURAL,8.101303e+12,CHAIMÁVIDA,30,5,5,CHAIMÁVIDA,22,3,CHAIMÁVIDA SOTO,ALDEA,3,Aldea,0,8.101010e+05,81012005.0,810130.0,810130005.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003403,4.815026e-07,"MULTIPOLYGON (((-72.87057 -36.86015, -72.87075..."
208180,208181,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,RURAL,8.101303e+12,CHAIMÁVIDA,30,5,5,CHAIMÁVIDA,22,6,CHAIMÁVIDA SOTO,ALDEA,3,Aldea,0,8.101010e+05,81012005.0,810130.0,810130005.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006658,1.699166e-06,"MULTIPOLYGON (((-72.87101 -36.86126, -72.87144..."
208181,208182,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,RURAL,8.101303e+12,CHAIMÁVIDA,30,11,11,EL PINO,47,4,EL PINO,ALDEA,3,Aldea,0,8.101020e+05,81012011.0,810130.0,810130011.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.005354,5.816337e-07,"MULTIPOLYGON (((-72.92233 -36.84186, -72.92245..."
208182,208183,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,RURAL,8.101303e+12,CHAIMÁVIDA,30,11,11,EL PINO,47,8,EL PINO,ALDEA,3,Aldea,0,8.101020e+05,81012011.0,810130.0,810130011.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002819,3.772647e-07,"MULTIPOLYGON (((-72.92084 -36.84379, -72.92074..."
208183,208184,8101,8,BIOBÍO,81,CONCEPCIÓN,CONCEPCIÓN,RURAL,8.101313e+12,LAS ULLOAS,31,13,13,LAS ULLOAS,56,1,JUAN RIQUELME,ALDEA,3,Aldea,0,8.101030e+05,81012013.0,810131.0,810131013.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.007864,3.990172e-07,"MULTIPOLYGON (((-72.95074 -36.80037, -72.95152..."

In [8]:
man_gdf.columns.tolist()

['OBJECTID',
 'CUT',
 'COD_REGION',
 'REGION',
 'COD_PROVINCIA',
 'PROVINCIA',
 'COMUNA',
 'AREA_C',
 'MANZENT',
 'DISTRITO',
 'COD_DISTRITO',
 'COD_LOCALIDAD',
 'COD_ZONA',
 'LOCALIDAD',
 'COD_ENTIDAD',
 'COD_MANZANA',
 'ENTIDAD',
 'TIPO_MZ',
 'COD_CATEGORIA',
 'CATEGORIA',
 'MZ_BASE_CENSO',
 'ID_ENTIDAD',
 'ID_LOCALIDAD',
 'ID_DISTRITO',
 'ID_ZONA',
 'n_per',
 'n_hombres',
 'n_mujeres',
 'n_edad_0_5',
 'n_edad_6_13',
 'n_edad_14_17',
 'n_edad_18_24',
 'n_edad_25_44',
 'n_edad_45_59',
 'n_edad_60_mas',
 'prom_edad',
 'n_inmigrantes',
 'n_nacionalidad',
 'n_pueblos_orig',
 'n_afrodescendencia',
 'n_lengua_indigena',
 'n_religion',
 'n_dificultad_ver',
 'n_dificultad_oir',
 'n_dificultad_mover',
 'n_dificultad_cogni',
 'n_dificultad_cuidado',
 'n_dificultad_comunic',
 'n_discapacidad',
 'n_estcivcon_casado',
 'n_estcivcon_conviviente',
 'n_estcivcon_conv_civil',
 'n_estcivcon_anul_sep_div',
 'n_estcivcon_viudo',
 'n_estcivcon_soltero',
 'prom_escolaridad18',
 'n_asistencia_parv',
 'n_asistencia_basica',
 'n_asistencia_media',
 'n_asistencia_superior',
 'n_cine_nunca_curso_primera_infancia',
 'n_cine_primaria',
 'n_cine_secundaria',
 'n_cine_terciaria_maestria_doctorado',
 'n_cine_especial_diferencial',
 'n_analfabet',
 'n_ocupado',
 'n_desocupado',
 'n_fuera_fuerza_trabajo',
 'n_cise_rec_independientes',
 'n_cise_rec_dependientes',
 'n_cise_rec_trabajador_no_remunerado',
 'n_ciuo_1',
 'n_ciuo_2',
 'n_ciuo_3',
 'n_ciuo_4',
 'n_ciuo_5',
 'n_ciuo_6',
 'n_ciuo_7',
 'n_ciuo_8',
 'n_ciuo_9',
 'n_ciuo_0',
 'n_caenes_A',
 'n_caenes_B',
 'n_caenes_C',
 'n_caenes_D',
 'n_caenes_E',
 'n_caenes_F',
 'n_caenes_G',
 'n_caenes_H',
 'n_caenes_I',
 'n_caenes_J',
 'n_caenes_K',
 'n_caenes_L',
 'n_caenes_M',
 'n_caenes_N',
 'n_caenes_O',
 'n_caenes_P',
 'n_caenes_Q',
 'n_caenes_R',
 'n_caenes_S',
 'n_caenes_T',
 'n_caenes_U',
 'n_transporte_auto',
 'n_transporte_publico',
 'n_transporte_camina',
 'n_transporte_bicicleta',
 'n_transporte_motocicleta',
 'n_transporte_cab_lan_bote',
 'n_transporte_otros',
 'n_hog',
 'prom_per_hog',
 'n_hog_unipersonales',
 'n_hog_60',
 'n_hog_menores',
 'n_jefatura_mujer',
 'n_tenencia_propia_pagada',
 'n_tenencia_propia_pagandose',
 'n_tenencia_arrendada_contrato',
 'n_tenencia_arrendada_sin_contrato',
 'n_tenencia_cedida_trabajo',
 'n_tenencia_cedida_familiar',
 'n_tenencia_otro',
 'n_comb_cocina_gas',
 'n_comb_cocina_parafina',
 'n_comb_cocina_lena',
 'n_comb_cocina_pellet',
 'n_comb_cocina_carbon',
 'n_comb_cocina_electricidad',
 'n_comb_cocina_solar',
 'n_comb_cocina_no_utiliza',
 'n_comb_calefaccion_gas',
 'n_comb_calefaccion_parafina',
 'n_comb_calefaccion_lena',
 'n_comb_calefaccion_pellet',
 'n_comb_calefaccion_carbon',
 'n_comb_calefaccion_electricidad',
 'n_comb_calefaccion_otra',
 'n_comb_calefaccion_no_utiliza',
 'n_serv_tel_movil',
 'n_serv_compu',
 'n_serv_tablet',
 'n_serv_internet_fija',
 'n_serv_internet_movil',
 'n_serv_internet_satelital',
 'n_internet',
 'n_vp',
 'n_vp_ocupada',
 'n_vp_desocupada',
 'n_tipo_viv_casa',
 'n_tipo_viv_depto',
 'n_tipo_viv_indigena',
 'n_tipo_viv_pieza',
 'n_tipo_viv_mediagua',
 'n_tipo_viv_movil',
 'n_tipo_viv_otro',
 'n_dormitorios_1',
 'n_dormitorios_2',
 'n_dormitorios_3',
 'n_dormitorios_4',
 'n_dormitorios_5',
 'n_dormitorios_6_o_mas',
 'n_viv_hacinadas',
 'n_viv_irrecuperables',
 'n_hog_allegados',
 'n_nucleos_hacinados_allegados',
 'n_viv_no_ampliables',
 'n_deficit_cuantitativo',
 'n_mat_paredes_hormigon',
 'n_mat_paredes_albanileria',
 'n_mat_paredes_tabique_forrado',
 'n_mat_paredes_tabique_sin_forro',
 'n_mat_paredes_artesanal',
 'n_mat_paredes_precarios',
 'n_mat_techo_tejas',
 'n_mat_techo_hormigon',
 'n_mat_techo_zinc',
 'n_mat_techo_fibrocemento',
 'n_mat_techo_fonolita',
 'n_mat_techo_paja',
 'n_mat_techo_precarios',
 'n_mat_techo_sin_cubierta',
 'n_mat_piso_radier_con_revestimiento',
 'n_mat_piso_radier_sin_revestimiento',
 'n_mat_piso_baldosa_cemento',
 'n_mat_piso_capa_cemento',
 'n_mat_piso_tierra',
 'n_fuente_agua_publica',
 'n_fuente_agua_pozo',
 'n_fuente_agua_camion',
 'n_fuente_agua_rio',
 'n_distrib_agua_llave',
 'n_distrib_agua_llave_fuera',
 'n_distrib_agua_acarreo',
 'n_serv_hig_alc_dentro',
 'n_serv_hig_alc_fuera',
 'n_serv_hig_fosa',
 'n_serv_hig_pozo',
 'n_serv_hig_acequia_canal',
 'n_serv_hig_cajon_otro',
 'n_serv_hig_bano_quimico',
 'n_serv_hig_bano_seco',
 'n_serv_hig_no_tiene',
 'n_fuente_elect_publica',
 'n_fuente_elect_diesel',
 'n_fuente_elect_solar',
 'n_fuente_elect_eolica',
 'n_fuente_elect_otro',
 'n_fuente_elect_no_tiene',
 'n_basura_servicios',
 'n_basura_entierra',
 'n_basura_eriazo',
 'n_basura_rio',
 'n_basura_otro',
 'SHAPE_Length',
 'SHAPE_Area',
 'SHAPE']

In [17]:
# man_gdf[man_gdf.PROVINCIA == "CONCEPCIÓN"].plot(figsize=(60,60), column="d_per", cmap="magma", vmax=370)

In [ ]:
per_df = pd.read_parquet("data/personas_censo2024.parquet")
# per_df = per_df[per_df.provincia == 81]
per_df = per_df[per_df.comuna == 8101]

In [55]:
prep_df = per_df[[]]
prep_df

Empty DataFrame
Columns: []
Index: [153, 154, 155, 270, 271, 272, 295, 296, 297, 298, 414, 415, 910, 911, 912, 1235, 1236, 1386, 1387, 1388, 1389, 1669, 1670, 1671, 1672, 1802, 1904, 1910, 1911, 1912, 2002, 2164, 2335, 2336, 2337, 2388, 2389, 2994, 2995, 3164, 3165, 3166, 3167, 3168, 3169, 3223, 3224, 3225, 3226, 3227, 3228, 4228, 4229, 4230, 4231, 4389, 4390, 4391, 4392, 4393, 4394, 4395, 4798, 4799, 4943, 4944, 5219, 5220, 5221, 5222, 5238, 5460, 5461, 5462, 5463, 5464, 5484, 5485, 5647, 5648, 5649, 5650, 5651, 5704, 5705, 6157, 6211, 6212, 6336, 6337, 6371, 6372, 6373, 6374, 6646, 6757, 6758, 6926, 6927, 7093, ...]

[230375 rows x 0 columns]

In [60]:
prep_df.loc[:,"n_per"] = 1
prep_df.loc[:,"n_hombres"] = (per_df.sexo == 1) * 1
prep_df.loc[:,"n_mujeres"] = (per_df.sexo == 2) * 1
prep_df.loc[:,"n_edad_0_5"] = (per_df.edad <= 5) * 1
prep_df.loc[:,"n_edad_6_13"] = ((per_df.edad >= 6) & (per_df.edad <= 13)) * 1
prep_df.loc[:,"n_edad_14_17"] = ((per_df.edad >= 14) & (per_df.edad <= 17)) * 1
prep_df.loc[:,"n_edad_18_24"] = ((per_df.edad >= 18) & (per_df.edad <= 24)) * 1
prep_df.loc[:,"n_edad_25_44"] = ((per_df.edad >= 25) & (per_df.edad <= 44)) * 1
prep_df.loc[:,"n_edad_45_59"] = ((per_df.edad >= 45) & (per_df.edad <= 59)) * 1
prep_df.loc[:,"n_edad_60_mas"] = (per_df.edad >= 60) * 1

#  'n_inmigrantes',
#  'n_nacionalidad',
#  'n_pueblos_orig',
#  'n_afrodescendencia',
#  'n_lengua_indigena',
#  'n_religion',
#  'n_dificultad_ver',
#  'n_dificultad_oir',
#  'n_dificultad_mover',
#  'n_dificultad_cogni',
#  'n_dificultad_cuidado',
#  'n_dificultad_comunic',
#  'n_discapacidad',
#  'n_estcivcon_casado',
#  'n_estcivcon_conviviente',
#  'n_estcivcon_conv_civil',
#  'n_estcivcon_anul_sep_div',
#  'n_estcivcon_viudo',
#  'n_estcivcon_soltero',
#  'prom_escolaridad18',
#  'n_asistencia_parv',
#  'n_asistencia_basica',
#  'n_asistencia_media',
#  'n_asistencia_superior',
#  'n_cine_nunca_curso_primera_infancia',
#  'n_cine_primaria',
#  'n_cine_secundaria',
#  'n_cine_terciaria_maestria_doctorado',
#  'n_cine_especial_diferencial',
#  'n_analfabet',
#  'n_ocupado',
#  'n_desocupado',
#  'n_fuera_fuerza_trabajo',
#  'n_cise_rec_independientes',
#  'n_cise_rec_dependientes',
#  'n_cise_rec_trabajador_no_remunerado',
#  'n_ciuo_1',
#  'n_ciuo_2',
#  'n_ciuo_3',
#  'n_ciuo_4',
#  'n_ciuo_5',
#  'n_ciuo_6',
#  'n_ciuo_7',
#  'n_ciuo_8',
#  'n_ciuo_9',
#  'n_ciuo_0',
#  'n_caenes_A',
#  'n_caenes_B',
#  'n_caenes_C',
#  'n_caenes_D',
#  'n_caenes_E',
#  'n_caenes_F',
#  'n_caenes_G',
#  'n_caenes_H',
#  'n_caenes_I',
#  'n_caenes_J',
#  'n_caenes_K',
#  'n_caenes_L',
#  'n_caenes_M',
#  'n_caenes_N',
#  'n_caenes_O',
#  'n_caenes_P',
#  'n_caenes_Q',
#  'n_caenes_R',
#  'n_caenes_S',
#  'n_caenes_T',
#  'n_caenes_U',
#  'n_transporte_auto',
#  'n_transporte_publico',
#  'n_transporte_camina',
#  'n_transporte_bicicleta',
#  'n_transporte_motocicleta',
#  'n_transporte_cab_lan_bote',
#  'n_transporte_otros',
#  'n_hog',
#  'prom_per_hog',
#  'n_hog_unipersonales',
#  'n_hog_60',
#  'n_hog_menores',
#  'n_jefatura_mujer',
#  'n_tenencia_propia_pagada',
#  'n_tenencia_propia_pagandose',
#  'n_tenencia_arrendada_contrato',
#  'n_tenencia_arrendada_sin_contrato',
#  'n_tenencia_cedida_trabajo',
#  'n_tenencia_cedida_familiar',
#  'n_tenencia_otro',
#  'n_comb_cocina_gas',
#  'n_comb_cocina_parafina',
#  'n_comb_cocina_lena',
#  'n_comb_cocina_pellet',
#  'n_comb_cocina_carbon',
#  'n_comb_cocina_electricidad',
#  'n_comb_cocina_solar',
#  'n_comb_cocina_no_utiliza',
#  'n_comb_calefaccion_gas',
#  'n_comb_calefaccion_parafina',
#  'n_comb_calefaccion_lena',
#  'n_comb_calefaccion_pellet',
#  'n_comb_calefaccion_carbon',
#  'n_comb_calefaccion_electricidad',
#  'n_comb_calefaccion_otra',
#  'n_comb_calefaccion_no_utiliza',
#  'n_serv_tel_movil',
#  'n_serv_compu',
#  'n_serv_tablet',
#  'n_serv_internet_fija',
#  'n_serv_internet_movil',
#  'n_serv_internet_satelital',
#  'n_internet',
#  'n_vp',
#  'n_vp_ocupada',
#  'n_vp_desocupada',
#  'n_tipo_viv_casa',
#  'n_tipo_viv_depto',
#  'n_tipo_viv_indigena',
#  'n_tipo_viv_pieza',
#  'n_tipo_viv_mediagua',
#  'n_tipo_viv_movil',
#  'n_tipo_viv_otro',
#  'n_dormitorios_1',
#  'n_dormitorios_2',
#  'n_dormitorios_3',
#  'n_dormitorios_4',
#  'n_dormitorios_5',
#  'n_dormitorios_6_o_mas',
#  'n_viv_hacinadas',
#  'n_viv_irrecuperables',
#  'n_hog_allegados',
#  'n_nucleos_hacinados_allegados',
#  'n_viv_no_ampliables',
#  'n_deficit_cuantitativo',
#  'n_mat_paredes_hormigon',
#  'n_mat_paredes_albanileria',
#  'n_mat_paredes_tabique_forrado',
#  'n_mat_paredes_tabique_sin_forro',
#  'n_mat_paredes_artesanal',
#  'n_mat_paredes_precarios',
#  'n_mat_techo_tejas',
#  'n_mat_techo_hormigon',
#  'n_mat_techo_zinc',
#  'n_mat_techo_fibrocemento',
#  'n_mat_techo_fonolita',
#  'n_mat_techo_paja',
#  'n_mat_techo_precarios',
#  'n_mat_techo_sin_cubierta',
#  'n_mat_piso_radier_con_revestimiento',
#  'n_mat_piso_radier_sin_revestimiento',
#  'n_mat_piso_baldosa_cemento',
#  'n_mat_piso_capa_cemento',
#  'n_mat_piso_tierra',
#  'n_fuente_agua_publica',
#  'n_fuente_agua_pozo',
#  'n_fuente_agua_camion',
#  'n_fuente_agua_rio',
#  'n_distrib_agua_llave',
#  'n_distrib_agua_llave_fuera',
#  'n_distrib_agua_acarreo',
#  'n_serv_hig_alc_dentro',
#  'n_serv_hig_alc_fuera',
#  'n_serv_hig_fosa',
#  'n_serv_hig_pozo',
#  'n_serv_hig_acequia_canal',
#  'n_serv_hig_cajon_otro',
#  'n_serv_hig_bano_quimico',
#  'n_serv_hig_bano_seco',
#  'n_serv_hig_no_tiene',
#  'n_fuente_elect_publica',
#  'n_fuente_elect_diesel',
#  'n_fuente_elect_solar',
#  'n_fuente_elect_eolica',
#  'n_fuente_elect_otro',
#  'n_fuente_elect_no_tiene',
#  'n_basura_servicios',
#  'n_basura_entierra',
#  'n_basura_eriazo',
#  'n_basura_rio',
#  'n_basura_otro',

prep_df

,n_per,n_hombres,n_mujeres,n_edad_0_5,n_edad_6_13,n_edad_14_17,n_edad_18_24,n_edad_25_44,n_edad_45_59,n_edad_60_mas
153,1,0,1,0,0,0,0,1,0,0
154,1,1,0,0,0,0,0,1,0,0
155,1,0,1,1,0,0,0,0,0,0
270,1,0,1,0,0,0,0,0,0,1
271,1,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
18480170,1,0,1,0,0,0,0,1,0,0
18480179,1,0,1,0,0,0,1,0,0,0
18480180,1,0,1,0,0,0,0,1,0,0
18480181,1,0,1,0,0,0,0,1,0,0
18480249,1,1,0,0,0,0,0,1,0,0

In [ ]:
viv_df = pd.read_parquet("data/viviendas_censo2024.parquet")
# viv_df = viv_df[viv_df.provincia == 81]
viv_df = viv_df[viv_df.comuna == 8101]

In [11]:
viv_df.columns.tolist()

['id_vivienda',
 'region',
 'provincia',
 'comuna',
 'comuna_bajo_umbral',
 'area',
 'tipo_operativo',
 'n_hog',
 'n_per',
 'p2_tipo_vivienda',
 'p3a_estado_ocupacion',
 'p3b_estado_ocupacion',
 'p4a_mat_paredes',
 'p4b_mat_techo',
 'p4c_mat_piso',
 'p5_num_dormitorios',
 'p6_fuente_agua',
 'p7_distrib_agua',
 'p8_serv_hig',
 'p9_fuente_elect',
 'p10_basura',
 'p11a_num_personas',
 'p11b_comparte_gasto',
 'p11c_num_hogar',
 'indice_hacinamiento']

In [10]:
viv_df.rename(columns={
    "cant_per": "n_per",
    "cant_hog": "n_hog",
}, inplace=True)
viv_df

,id_vivienda,region,provincia,comuna,comuna_bajo_umbral,area,tipo_operativo,n_hog,n_per,p2_tipo_vivienda,p3a_estado_ocupacion,p3b_estado_ocupacion,p4a_mat_paredes,p4b_mat_techo,p4c_mat_piso,p5_num_dormitorios,p6_fuente_agua,p7_distrib_agua,p8_serv_hig,p9_fuente_elect,p10_basura,p11a_num_personas,p11b_comparte_gasto,p11c_num_hogar,indice_hacinamiento
63,64,8,81,8101,2,1,2,1.0,3,3.0,1.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,NaN,1.0
114,115,8,81,8101,2,1,2,1.0,3,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,NaN,1.0
125,126,8,81,8101,2,1,2,1.0,4,3.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0,NaN,1.0
176,177,8,81,8101,2,1,2,1.0,1,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
177,178,8,81,8101,2,1,2,1.0,1,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7664132,7664133,8,81,8101,2,1,2,1.0,3,1.0,1.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,NaN,1.0
7664141,7664142,8,81,8101,2,1,2,1.0,1,3.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
7664351,7664352,8,81,8101,2,1,2,1.0,2,3.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,NaN,1.0
7664355,7664356,8,81,8101,2,1,2,1.0,3,3.0,1.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,NaN,1.0
7664386,7664387,8,81,8101,2,1,2,1.0,1,3.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0

---
# Simulated Annealing

In [68]:
attributes = [
    "n_per",
    "n_hombres",
    "n_mujeres",
    "n_edad_0_5",
    "n_edad_6_13",
    "n_edad_14_17",
    "n_edad_18_24",
    "n_edad_25_44",
    "n_edad_45_59",
    "n_edad_60_mas"
]

attributes

['n_per',
 'n_hombres',
 'n_mujeres',
 'n_edad_0_5',
 'n_edad_6_13',
 'n_edad_14_17',
 'n_edad_18_24',
 'n_edad_25_44',
 'n_edad_45_59',
 'n_edad_60_mas']

In [69]:
totals = prep_df[attributes].sum()
totals

n_per            230375
n_hombres        110985
n_mujeres        119390
n_edad_0_5        10495
n_edad_6_13       18900
n_edad_14_17       9617
n_edad_18_24      30203
n_edad_25_44      74105
n_edad_45_59      39981
n_edad_60_mas     47074
dtype: int64

In [97]:
def objetivo(m, a):
    return m[a] * totals[a] / man_gdf.loc[:, a].sum()

In [111]:
objetivo(man_gdf.iloc[0], attributes[0])

np.float64(19.36643865920997)

---

In [10]:
hog_df = pd.read_parquet("hogares_censo2024.parquet")
hog_df = hog_df[hog_df.provincia == 81]
hog_df

,id_vivienda,id_hogar,region,provincia,comuna,comuna_bajo_umbral,area,tipo_operativo,p12_tenencia_viv,p13_comb_cocina,p14_comb_calefaccion,p15a_serv_tel_movil,p15b_serv_compu,p15c_serv_tablet,p15d_serv_internet_fija,p15e_serv_internet_movil,p15f_serv_internet_satelital,tipologia_hogar
6,7,1,8,81,8111,2,2,2,6.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,4.0
52,64,1,8,81,8101,2,1,2,2.0,1.0,6.0,1.0,1.0,2.0,1.0,1.0,2.0,4.0
59,73,1,8,81,8108,2,1,2,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,4.0
62,77,1,8,81,8102,2,1,2,3.0,1.0,6.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0
71,88,1,8,81,8110,2,1,2,2.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6622504,7664356,1,8,81,8101,2,1,2,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,7.0
6622511,7664364,1,8,81,8102,2,1,2,2.0,1.0,3.0,1.0,1.0,2.0,1.0,1.0,2.0,4.0
6622527,7664387,1,8,81,8101,2,1,2,2.0,1.0,8.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0
6622538,7664398,1,8,81,8112,2,1,2,1.0,1.0,4.0,1.0,2.0,2.0,1.0,1.0,2.0,5.0
6622576,7664444,1,8,81,8108,2,1,2,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0